# Generated by Django 3.2.5 on 2021-09-14 23:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('pass_hash', models.CharField(blank=True, max_length=200, verbose_name='pass_hash')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HandstandClassic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_in_path', models.CharField(blank=True, max_length=200, verbose_name='Путь к входящему фото')),
                ('result', models.CharField(blank=True, max_length=200, verbose_name='Результат')),
                ('img_out_path', models.CharField(blank=True, max_length=200, verbose_name='Путь к обработанному фото')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bsuser')),
            ],
        ),
        migrations.CreateModel(
            name='HsCResInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WES', models.TextField(blank=True, max_length=300, verbose_name='Путь к WES проблемам')),
                ('WSH', models.TextField(blank=True, max_length=300, verbose_name='Путь к WSH проблемам')),
                ('WSK', models.TextField(blank=True, max_length=300, verbose_name='Путь к WSK проблемам')),
                ('SHK', models.TextField(blank=True, max_length=300, verbose_name='Путь к SHK проблемам')),
                ('HKA', models.TextField(blank=True, max_length=300, verbose_name='Путь к HKA проблемам')),
                ('WHA', models.TextField(blank=True, max_length=300, verbose_name='Путь к WHA проблемам')),
                ('users_handstandC', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.handstandclassic')),
            ],
        ),
        migrations.CreateModel(
            name='BSUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='users_avatars')),
                ('age', models.IntegerField(blank=True, default=18, null=True, verbose_name='возраст')),
                ('aboutMe', models.TextField(blank=True, max_length=512, verbose_name='о себе')),
                ('gender', models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=1, verbose_name='пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bsuser')),
            ],
        ),
    ]
